# Tf 2.x low level API

In [1]:
import tensorflow as tf

In [2]:
# What is keras? is it High level API or Low level?

## High level API 

## tensor constant

### Tensor: Multi dim arrays

In [3]:
const = tf.constant(43)

In [4]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [5]:
const.numpy()


43

In [6]:
## specify the datatype
const = tf.constant(43, dtype=tf.int64)
const

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [7]:
const_mat = tf.constant([[4,2],[9,5]])
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [8]:
const_mat.shape

TensorShape([2, 2])

In [9]:
const_mat.dtype

tf.int32

`observe: Increase the no. hidden layers and observe what happens to size of the model that you save.

Query: Before and after training will the model size will remain same or increase or decrease? ==> remains same`

## Commonly used method

In [10]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
5 * tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

In [12]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## add operations

In [13]:
const1 = tf.constant([[11,3,4],[3,4,5]])
const2 = tf.constant([[7,9,5],[3,4,5]])

In [14]:
result = tf.add(const1, const2)
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

In [15]:
const1 + const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

## Random const

In [16]:
x = tf.random.normal(shape=(2,2), mean=0, stddev=1.0)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.21976377, -0.48498598],
       [-0.16503073,  1.766549  ]], dtype=float32)>

In [17]:
x = tf.random.uniform(shape=(2,2), minval=0, maxval=10)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.8732705, 4.8749423],
       [1.3492656, 4.393697 ]], dtype=float32)>

In [18]:
x = tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [0, 6]], dtype=int32)>

## Variables



In [19]:
var1 = tf.Variable(45)

var2 = tf.Variable([[4,2],[9,5]])

In [20]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

In [21]:
var1.numpy()

45

In [22]:
var1 = tf.Variable(45.4)
var1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.4>

In [23]:
var1 = tf.Variable(45.4, dtype=tf.float16)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=45.4>

reassign a variable, var.assign()

In [24]:
var1 = tf.Variable(45.4, dtype=tf.float16)

In [25]:
var1.assign(99)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=99.0>

### reshaping operation

In [26]:
tensor = tf.Variable([[[10, 11, 12], [13, 15, 18]],[[10, 11, 12], [13, 15, 18]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [27]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [28]:
reshape_val = tf.reshape(tensor, [2,6])
reshape_val

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 15, 18],
       [10, 11, 12, 13, 15, 18]], dtype=int32)>

In [29]:
reshape_val = tf.reshape(tensor, [1,12])
reshape_val

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[10, 11, 12, 13, 15, 18, 10, 11, 12, 13, 15, 18]], dtype=int32)>

## Rank of tensor

no of dimensions, 

In [30]:
tf.rank(reshape_val)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [31]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [32]:
tensor[0, 1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [33]:
tensor[0,:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [15, 18]], dtype=int32)>

## more mathematical operations

In [34]:
a = tf.random.normal((2,2))
b = tf.random.normal((2,2))


c = a + b

In [35]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.21835436,  1.5117147 ],
       [-0.78698915,  1.6991525 ]], dtype=float32)>

In [36]:
tf.square(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.04767863, 2.2852814 ],
       [0.6193519 , 2.887119  ]], dtype=float32)>

In [37]:
tf.exp(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2440277, 4.534499 ],
       [0.4552133, 5.4693103]], dtype=float32)>

In [38]:
# Element wise multiplication - 
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [39]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[100, 121, 144],
        [169, 225, 324]],

       [[100, 121, 144],
        [169, 225, 324]]], dtype=int32)>

## Boradcasting in Tensorflow -


In [40]:
scaler = 4
scaler * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[40, 44, 48],
        [52, 60, 72]],

       [[40, 44, 48],
        [52, 60, 72]]], dtype=int32)>

In [41]:
scaler + tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[14, 15, 16],
        [17, 19, 22]],

       [[14, 15, 16],
        [17, 19, 22]]], dtype=int32)>

In [42]:
scaler - tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ -6,  -7,  -8],
        [ -9, -11, -14]],

       [[ -6,  -7,  -8],
        [ -9, -11, -14]]], dtype=int32)>

# Matrix multiplication

In [43]:
mat_u = tf.constant([[6,7,7]])
mat_v = tf.constant([[3,4,3]])

In [44]:
mat_u.shape

TensorShape([1, 3])

In [45]:
mat_v.shape

TensorShape([1, 3])

In [46]:
tf.transpose(mat_v).shape

TensorShape([3, 1])

In [47]:
mat_u.numpy()

array([[6, 7, 7]], dtype=int32)

In [48]:
tf.transpose(mat_v).numpy()

array([[3],
       [4],
       [3]], dtype=int32)

In [49]:
tf.matmul(mat_u, tf.transpose(mat_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [50]:
tf.matmul(tf.transpose(mat_v), mat_u)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 21],
       [24, 28, 28],
       [18, 21, 21]], dtype=int32)>

In [51]:
tf.transpose(mat_v) @ mat_u ### <<< Matrix mul

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 21],
       [24, 28, 28],
       [18, 21, 21]], dtype=int32)>

In [52]:
mat_u @ tf.transpose(mat_v) ### <<< Matrix mul


<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [53]:
mat_u * mat_v # element wise multiplication

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[18, 28, 21]], dtype=int32)>

## Casting method in tensorflow to change the datatype

In [54]:
tf.cast(mat_u, dtype=tf.int16) ### < can be utilized in quantization

<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[6, 7, 7]], dtype=int16)>

In [55]:
tf.cast(tf.constant(444.1324), dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=444>

## Ragged tensors
nested variable length arrays

In [56]:
ragged = tf.ragged.constant([[1,2,3,4,5], [], [1,2,3]])

In [57]:
# ragged = tf.constant([[1,2,3,4,5], [], [1,2,3]])


In [58]:
ragged.shape

TensorShape([3, None])

In [59]:
ragged[0, :].shape

TensorShape([5])

In [60]:
ragged[1, :].shape


TensorShape([0])

In [61]:
ragged[2, :].shape


TensorShape([3])

## Squared difference of tensors

In [62]:
varx = [1,2,3,4,5,6]
vary = 2

tf.math.squared_difference(varx, vary)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  0,  1,  4,  9, 16], dtype=int32)>

In [63]:
pred = [1,2,3,4,5,6]
actual = [1,1,1,1,1,1]

tf.math.squared_difference(pred, actual)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25], dtype=int32)>

## calculate mean

In [64]:
num = tf.constant([[1,2],[3,4]], dtype=tf.float32)
num

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [65]:
tf.reduce_mean(num)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [66]:
tf.reduce_mean(num, axis=0) # row wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [67]:
tf.reduce_mean(num, axis=1) # col wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [68]:
tf.reduce_mean(num, axis=1, keepdims=True) # col wise mean

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>